services:
  # Frontend (Static Site)
  - type: web
    name: zoophilist-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend (Web Service) 
  - type: web
    name: zoophilist-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: server
    env: node
